--- 
- 
  hosts: all
  tasks: 
    - 
      debug: var=ansible_hostname
      name: hostname
    - 
      debug: 
        msg: |-
            {{ msg.split('
            ') }}
      name: "date and time"
      vars: 
        msg: |
            Date: {{ ansible_date_time.date }}
            Timezone: {{ ansible_date_time.tz }}
    - 
      debug: 
        msg: |-
            {{ msg.split('
            ') }}
      name: "network info"
      vars: 
        msg: |
            All Interface List: {{ ansible_interfaces }}
            All IP: {{ ansible_all_ipv4_addresses }}
            Gateway: {{ ansible_default_ipv4.gateway }}
            Eth0 MAC: {{ ansible_eth0.macaddress }}
    - 
      debug: 
        msg: |-
            {{ msg.split('
            ') }}
      name: "OS and Kernel info"
      vars: 
        msg: |
            Distribution: {{ ansible_distribution }}
            Release: {{ ansible_distribution_release }}
            Distribution Version: {{ ansible_distribution_version }}
            Kernel: {{ ansible_kernel }}
            Architecture: {{ ansible_architecture }}
    - 
      debug: 
        msg: |-
            {{ msg.split('
            ') }}
      name: "HW info"
      vars: 
        msg: |
            CPU: {{ ansible_processor }}
            CPU Core: {{ ansible_processor_cores }}
            RAM: {{ ansible_memtotal_mb }}
            SWAP: {{ ansible_memory_mb.swap.total }}
